import { Product } from "./types";

export const dummyProducts: Product[] = [
  {
    id: "1",
    name: "هاتف سامسونج",
    title: "هاتف سامسونج",
    price: 299,
    imageUrl: "https://via.placeholder.com/600x400?text=%D9%87%D8%A7%D8%AA%D9%81+%D8%B3%D8%A7%D9%85%D8%B3%D9%88%D9%86",
    image: "📱",
    description: "هاتف ذكي مع كاميرا عالية الدقة",
    sellerId: "seller1",
  },
  {
    id: "2",
    name: "لابتوب ديل",
    title: "لابتوب ديل",
    price: 899,
    imageUrl: "https://via.placeholder.com/600x400?text=%D9%84%D8%A7%D8%A8%D8%AA%D9%88%D8%A8+%D8%AF%D9%8A%D9%84",
    image: "💻",
    description: "حاسوب محمول قوي للعمل والدراسة",
    sellerId: "seller2",
  },
  {
    id: "3",
    name: "سماعات",
    title: "سماعات",
    price: 59,
    imageUrl: "https://via.placeholder.com/600x400?text=%D8%B3%D9%85%D8%A7%D8%B9%D8%A7%D8%AA",
    image: "🎧",
    description: "سماعات مريحة وصوت نقي",
    sellerId: "seller3",
  },
  {
    id: "4",
    name: "ساعة ذكية",
    title: "ساعة ذكية",
    price: 179,
    imageUrl: "https://via.placeholder.com/600x400?text=%D8%B3%D8%A7%D8%B9%D8%A9+%D8%B0%D9%83%D9%8A%D8%A9",
    image: "⌚",
    description: "ساعة ذكية مع تتبع اللياقة",
    sellerId: "seller1",
  },
  {
    id: "5",
    name: "كاميرا",
    title: "كاميرا",
    price: 499,
    imageUrl: "https://via.placeholder.com/600x400?text=%D9%83%D8%A7%D9%85%D9%8A%D8%B1%D8%A7",
    image: "📷",
    description: "كاميرا عالية الوضوح للتصوير الاحترافي",
    sellerId: "seller3",
  },
  {
    id: "6",
    name: "حقيبة",
    title: "حقيبة",
    price: 45,
    imageUrl: "https://via.placeholder.com/600x400?text=%D8%AD%D9%82%D9%8A%D8%A8%D8%A9",
    image: "🎒",
    description: "حقيبة أنيقة ومناسبة لجميع الأغراض",
    sellerId: "seller4",
  },
];
